AWSTemplateFormatVersion: 2010-09-09
Description: >-
  S3 Template: S3 Bucket and Bucket Policy 

# This template creates:
#   S3 Bucket
#   S3 Bucket Policy

Parameters:

  BucketName:
    Description: Your S3 Bucket name
    Type: String


######################
# Resources section
######################

Resources:

  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Suspended 
      # CorsConfiguration: 
      #   CorsRules: 
      #   - AllowedHeaders: 
      #       - '*'
      #   - AllowedMethods: 
      #       - GET
      #   - AllowedOrigins: 
      #       - '*'
      #   - MaxAge: 3000

######################
# Outputs section
######################

Outputs:
  
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref S3Bucket
    Export:
      Name: !Sub '${AWS::StackName}-S3BucketName'